export const EMPRESA_CHANGED_INIT = "EMPRESA_CHANGED_INIT";
export const EMPRESA_CHANGED_FINISHED = "EMPRESA_CHANGED_FINISHED";

export const SUCURSAL_CHANGED = "SUCURSAL_CHANGED";

export const RELOAD_EMPRESAS_INIT = "RELOAD_EMPRESAS_INIT";
export const EMPRESAS_RELOADED = "EMPRESAS_RELOADED";
export const LOGIN_INIT = "LOGIN_INIT";
export const LOGGED_IN = "LOGGED_IN";

