# This workflow will build the app , run tests and then publish to heroku.


name: Buid and test

on: [push]
   

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test     
            

