# This workflow will build the app , run tests and then publish to heroku.


name: Publish to Heroku

on: [push]
   

jobs:
  publish-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: git config --local user.name ""
      - name: Deploy to Heroku
        env:
         HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        if: github.ref == 'refs/heads/master'
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/facturacion-frontend-dev.git origin/master:master
        
            

