# This workflow will build the app , run tests and then publish to heroku.


name: Publish to Heroku

on: [push]
   

jobs:
  publish-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test 
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.0.5
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "facturacion-frontend-dev" #Must be unique in Heroku
          heroku_email: "javier01123@gmail.com"
          buildpack: "" #OPTIONAL
          branch: "mater" #OPTIONAL and DEFAULT - 'HEAD' (a.k.a your current branch)
          dontuseforce: false #OPTIONAL and DEFAULT - false
          usedocker: false #OPTIONAL and DEFAULT - false
          appdir: "" #OPTIONAL and DEFAULT - "". This is useful if the api you're deploying is in a subfolder
          docker_heroku_process_type: "" #OPTIONAL and DEFAULT - "web"
               
            

